"use client";

import { useCallback, useEffect, useState } from "react";
import { supabaseClient } from "@/lib/supabase/client";
import LoadingState from "@/components/ui/LoadingState";
import EmptyState from "@/components/ui/EmptyState";
import StatusBadge from "@/components/ui/StatusBadge";

type Payment = { id: string; customer_id: string; amount_cents: number; reference: string; status: string;
  submitted_at: string; reviewed_at: string | null; review_reason: string | null; financial_transaction_id: string | null };
type CustomerFinance = { issuances: Array<{id:string;amount_cents:number;source_type:string;status:string;expires_at:string;financial_transaction_id:string|null}>; redemptions:Array<{id:string;amount_cents:number;trip_id:string}>; referrals:Array<{id:string;status:string;referrer_customer_id:string;referee_customer_id:string;qualifying_trip_id:string|null}>; trips:Array<{id:string;status:string;phase5_ride_fare_cents:number;phase5_service_fee_cents:number;phase5_membership_waiver_cents:number;phase5_credit_cents:number;phase5_customer_total_cents:number;phase5_driver_fare_basis_cents:number}> };

export default function AdminMoovuPlusPage() {
  const [rows,setRows]=useState<Payment[]>([]); const [loading,setLoading]=useState(true);
  const [busy,setBusy]=useState<string|null>(null); const [message,setMessage]=useState("");
  const [customerId,setCustomerId]=useState(""); const [finance,setFinance]=useState<CustomerFinance|null>(null);
  const token=useCallback(async()=>(await supabaseClient.auth.getSession()).data.session?.access_token ?? "",[]);
  const load=useCallback(async()=>{ setLoading(true); const t=await token(); const r=await fetch("/api/admin/phase5-memberships",{cache:"no-store",headers:{Authorization:`Bearer ${t}`}}); const j=await r.json().catch(()=>null); if(r.ok)setRows(j.payments??[]); else setMessage(j?.error||"Could not load MOOVU+ reviews."); setLoading(false); },[token]);
  useEffect(()=>{const timer=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(timer)},[load]);
  async function approve(payment:Payment){ const reason=window.prompt("Approval reason (verified Transfer/EFT):", "Verified Transfer/EFT payment"); if(!reason||reason.trim().length<3)return; setBusy(payment.id); const t=await token(); const r=await fetch("/api/admin/phase5-memberships",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({paymentId:payment.id,reason})}); const j=await r.json().catch(()=>null); setMessage(r.ok?"Membership payment approved and membership activated.":j?.error||"Approval failed."); setBusy(null); if(r.ok)await load(); }
  async function reject(payment:Payment){const reason=window.prompt("Rejection reason:");if(!reason||reason.trim().length<3)return;setBusy(payment.id);const t=await token();const r=await fetch("/api/admin/phase5-memberships",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({action:"reject",paymentId:payment.id,reason})});const j=await r.json().catch(()=>null);setMessage(r.ok?"Membership payment rejected.":j?.error||"Rejection failed.");setBusy(null);if(r.ok)await load()}
  async function inspectCustomer(){const t=await token();const r=await fetch(`/api/admin/phase5-credits?customerId=${encodeURIComponent(customerId.trim())}`,{cache:"no-store",headers:{Authorization:`Bearer ${t}`}});const j=await r.json().catch(()=>null);if(r.ok)setFinance(j);else setMessage(j?.error||"Customer finance lookup failed.")}
  async function issueCredit(){const value=window.prompt("Promotional credit amount in rand:");const reason=window.prompt("Adjustment reason:");const amountCents=Math.round(Number(value)*100);if(!reason||reason.trim().length<3||!Number.isSafeInteger(amountCents))return;const t=await token();const r=await fetch("/api/admin/phase5-credits",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({action:"issue",customerId:customerId.trim(),amountCents,requestId:crypto.randomUUID(),reason})});const j=await r.json().catch(()=>null);setMessage(r.ok?"Promotional credit issued.":j?.error||"Credit adjustment failed.");if(r.ok)await inspectCustomer()}
  async function reverseCredit(id:string){const reason=window.prompt("Reversal reason:");if(!reason||reason.trim().length<3)return;const t=await token();const r=await fetch("/api/admin/phase5-credits",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({action:"reverse",issuanceId:id,reason})});const j=await r.json().catch(()=>null);setMessage(r.ok?"Unspent promotional credit reversed.":j?.error||"Credit reversal failed.");if(r.ok)await inspectCustomer()}
  if(loading)return <LoadingState title="Loading MOOVU+" description="Preparing membership payment reviews."/>;
  return <main className="space-y-6 text-black"><header className="moovu-card p-6"><div className="moovu-section-title">Customer monetisation</div><h1 className="mt-2 text-3xl font-black">MOOVU+ memberships</h1><p className="mt-2 text-sm text-slate-600">Review verified R99 Transfer/EFT submissions. A submission alone never activates membership.</p></header>
    {message?<p role="status" className="rounded-2xl bg-amber-50 p-4 font-bold text-amber-900">{message}</p>:null}
    {!rows.length?<EmptyState title="No membership payments" description="Submitted MOOVU+ payments will appear here."/>:<section className="grid gap-4">{rows.map(row=><article key={row.id} className="moovu-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-black">R{(row.amount_cents/100).toFixed(2)} · {row.reference}</h2><p className="mt-1 text-xs text-slate-500">Customer {row.customer_id} · {new Date(row.submitted_at).toLocaleString()}</p></div><StatusBadge status={row.status.toLowerCase()}/></div>{row.review_reason?<p className="mt-3 text-sm text-slate-600">{row.review_reason}</p>:null}{row.financial_transaction_id?<p className="mt-2 text-xs text-slate-500">Financial transaction: {row.financial_transaction_id}</p>:null}{row.status==="SUBMITTED"?<div className="mt-4 flex gap-2"><button disabled={busy===row.id} className="moovu-btn moovu-btn-primary" onClick={()=>void approve(row)}>Approve verified payment</button><button disabled={busy===row.id} className="moovu-btn moovu-btn-secondary" onClick={()=>void reject(row)}>Reject</button></div>:null}</article>)}</section>}
    <section className="moovu-card p-6"><h2 className="text-xl font-black">Customer Phase 5 finance</h2><p className="mt-1 text-sm text-slate-600">Inspect credit, referrals and trip snapshots before making a bounded adjustment.</p><div className="mt-4 flex flex-wrap gap-2"><input className="moovu-input min-w-72 flex-1" value={customerId} onChange={(event)=>setCustomerId(event.target.value)} placeholder="Customer UUID"/><button className="moovu-btn moovu-btn-secondary" onClick={()=>void inspectCustomer()}>Inspect</button><button className="moovu-btn moovu-btn-primary" onClick={()=>void issueCredit()}>Issue credit</button></div>{finance?<div className="mt-5 grid gap-4 lg:grid-cols-3"><div><h3 className="font-black">Credit</h3>{finance.issuances.map(row=><div key={row.id} className="mt-2 rounded-xl bg-slate-50 p-3 text-xs"><strong>R{(row.amount_cents/100).toFixed(2)} · {row.status}</strong><br/>{row.source_type} · expires {new Date(row.expires_at).toLocaleDateString()}<br/>{row.financial_transaction_id||"No transaction"}{row.status==="ACTIVE"?<button className="mt-2 block font-bold text-red-700" onClick={()=>void reverseCredit(row.id)}>Reverse unspent credit</button>:null}</div>)}</div><div><h3 className="font-black">Referrals</h3>{finance.referrals.map(row=><div key={row.id} className="mt-2 rounded-xl bg-slate-50 p-3 text-xs">{row.status}<br/>Referrer {row.referrer_customer_id}<br/>Referee {row.referee_customer_id}<br/>{row.qualifying_trip_id||"Not qualified"}</div>)}</div><div><h3 className="font-black">Trip snapshots</h3>{finance.trips.map(row=><div key={row.id} className="mt-2 rounded-xl bg-slate-50 p-3 text-xs">{row.status} · {row.id}<br/>Ride R{(row.phase5_ride_fare_cents/100).toFixed(2)} · fee R{(row.phase5_service_fee_cents/100).toFixed(2)} · waiver R{(row.phase5_membership_waiver_cents/100).toFixed(2)} · credit R{(row.phase5_credit_cents/100).toFixed(2)}<br/>Customer R{(row.phase5_customer_total_cents/100).toFixed(2)} · Driver basis R{(row.phase5_driver_fare_basis_cents/100).toFixed(2)}</div>)}</div></div>:null}
    </section>
  </main>;
}


