-- MOOVU live trip telemetry and actual-fare foundation (REVIEW ONLY)
-- Apply to staging first. Location history contains sensitive personal data.

alter table public.trips add column if not exists trip_started_at timestamptz;
alter table public.trips add column if not exists current_fare numeric(12,2);
alter table public.trips add column if not exists actual_distance_km numeric(12,3) not null default 0;
alter table public.trips add column if not exists actual_duration_min numeric(12,2) not null default 0;
alter table public.trips add column if not exists actual_route_source text;
alter table public.trips add column if not exists actual_fare_breakdown jsonb;
alter table public.trips add column if not exists fare_last_recalculated_at timestamptz;

create table if not exists public.trip_live_locations (
  trip_id uuid primary key references public.trips(id) on delete cascade,
  driver_id uuid not null references public.drivers(id) on delete cascade,
  lat double precision not null,
  lng double precision not null,
  heading double precision,
  speed_mps double precision,
  accuracy_m double precision,
  captured_at timestamptz not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.trip_location_points (
  id bigint generated by default as identity primary key,
  trip_id uuid not null references public.trips(id) on delete cascade,
  driver_id uuid not null references public.drivers(id) on delete cascade,
  lat double precision not null,
  lng double precision not null,
  heading double precision,
  speed_mps double precision,
  accuracy_m double precision,
  segment_distance_km numeric(12,6) not null default 0,
  captured_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists trip_location_points_trip_time_idx
  on public.trip_location_points(trip_id, captured_at desc);
create index if not exists trip_live_locations_driver_idx
  on public.trip_live_locations(driver_id, captured_at desc);

alter table public.trip_live_locations enable row level security;
alter table public.trip_location_points enable row level security;
-- Writes remain server-only. Customer/admin reads should use authorized API routes,
-- not broad browser policies. Retention should be agreed before production rollout.

